# Generated by Django 5.2.11 on 2026-06-07 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('item', models.ImageField(upload_to='clothes/')),
                ('tier', models.CharField(choices=[('NON-VIP', 'Non-VIP'), ('VIP', 'VIP')], default='NON-VIP', max_length=10)),
            ],
        ),
    ]
